### ISSUE TITLE
[JOSS] Better API Documentation

### ISSUE THREAD

**Issue by ljvmiranda921** [NiaOrg/NiaPy#120]
1. Stylistically, it may be better to pattern the docstring with the standard template found [here](https://pythonhosted.org/an_example_pypi_project/sphinx.html#function-definitions). This is so that it will render properly in your [API Documentation](http://niapy.readthedocs.io/en/latest/api/algorithms.html#module-NiaPy.algorithms.basic).

Another option is to use the [`numpydoc` extension](https://github.com/numpy/numpydoc), which gives a prettier format inside your docstrings. 

2. It's also useful to add docstrings on some of your class methods. For example, [this method](http://niapy.readthedocs.io/en/stable/_modules/NiaPy/algorithms/basic/ga.html#GeneticAlgorithm.checkForBest) doesn't have any docstring/documentation.
--- 
This is an issue related to openjournals/joss-reviews#613

**Comment by lucijabrezocnik** [comment]
Hi @ljvmiranda921 ,

We have added missing documentation to the classes. 

Regarding the style of docstring pattern, we revised your recommendation and concluded to update our docstring following one of the proposed options in one of the future releases.

Please check out and confirm the changes we made in referenced PR #125 before we merge them into the master branch.

Thank you!

**Comment by ljvmiranda921** [comment]
> Regarding the style of docstring pattern, we revised your recommendation and concluded to update our docstring following one of the proposed options in one of the future releases.

No problem.

> We have added missing documentation to the classes.
> Please check out and confirm the changes we made in referenced PR #125 before we merge them into the master branch.

The descriptions can be more verbose in the future but this looks good to me already. I believe you can already merge to master.

**Comment by lucijabrezocnik** [comment]
Thank you for your fast response @ljvmiranda921 ! 

We will add more verbose descriptions in the next release 👍
