### ISSUE TITLE
[JOSS] (Optional) Follow PEP-8 style guide in naming methods

### ISSUE THREAD

**Issue by ljvmiranda921** [NiaOrg/NiaPy#123]
This is prescriptive and optional, but I personally find this very important. Please follow [PEP8](https://www.python.org/dev/peps/pep-0008/#package-and-module-names) as a prescriptive guide.

- Methods usually have lower-case characters separated by underscores. `TournamentSelection` should be `tournament_selection`. Check [this](https://www.python.org/dev/peps/pep-0008/#function-and-variable-names).
- The package name should be in lower-case. `NiaPy` should be `niapy`. Check [this](https://www.python.org/dev/peps/pep-0008/#package-and-module-names).

--- 
This is an issue related to openjournals/joss-reviews#613

**Comment by GregaVrbancic** [comment]
Thank you for recommendations and provided links to resources. We will most definitely go through PEP8 - code style guide and refactor our code in one of the next releases, to be in line with best practices and style conventions.

**Comment by firefly-cpp** [comment]
@zStupan is now working on this.

**Comment by GregaVrbancic** [comment]
If this issue would be addressed, It would be quite nice to include at the same time also the potential dropping of Python 2.7.

**Comment by zStupan** [comment]
I'm currently working on reformatting the code, and also changing the current legacy random number generation to the [new preferred way in numpy](https://numpy.org/doc/stable/reference/random/index.html) using numpy.random.Generator. And also switching to the PCG64  PRNG which offers better performance and a higher statistical quality compared to MT19937. This is supported in numpy 1.17 and up, so it won't work with python 2.

It should be done by the end of the week.

**Comment by GregaVrbancic** [comment]
@zStupan great work! I cannot express myself how much everyone contributing to this project appreciates your work.

**Comment by firefly-cpp** [comment]
Hello @ljvmiranda921. It's good to hear from you. As you can see, your issue is still open. :)

Hopefully, we will finally close this issue soon.

**Comment by zStupan** [comment]
Hello everyone, thank you for the kind words.

Unfortunately the reformatting is not going as smoothly as I had hoped. There is a lot of code, with a lot of warnings, it  could take a while. But I'm getting through it, slowly but surely. It's tough, because it's easy to break the code even when using automated tools  for refactoring.

But as @firefly-cpp  said, hopefully soon we'll be able  to close this issue. I also recommend that a section of the contributing guide is dedicated to the code  style.

**Comment by firefly-cpp** [comment]
Hello @zStupan - can you please inform us about your progress in solving this issue?

**Comment by sisco0** [comment]
Should this be enforced by Pylint? (see http://pylint.pycqa.org/en/latest/user_guide/options.html)

**Comment by zStupan** [comment]
Hello everyone,
I'm still working on this don't worry :smile:. @sisco0  I agree with the addition of pep8-naming. I will also re-enable most checks in the flake 8 settings. 
In fact, the only warning I'd ignore is "Line too long". In PEP8 the line length is supposed to be limited to 79 characters. I feel like that makes the code crammed and unreadable as the line gets broken up awkwardly.

**Comment by firefly-cpp** [comment]
Fixed in #309
