### ISSUE TITLE
Documentation improvements

### ISSUE THREAD

**Issue by GregaVrbancic** [NiaOrg/NiaPy#155]
Documentation improvements (incomplete documentation):

**Algorithms basic:**

- [x] Genetic Algorithm
- [ ] EvolutionStrategy1p1
   - Missing reference URL
   - Missing reference paper 
- [ ] EvolutionStrategyMp1
   - Missing reference URL
   - Missing reference paper 
- [ ] EvolutionStrategyMpL
   - Missing reference URL
   - Missing reference paper 
- [ ] EvolutionStrategyML
   - Missing reference URL
   - Missing reference paper 
- [x] KrillHerdV11

**Algorithms other:**

- [ ] SimulatedAnnealing
   - Missing reference URL
   - Missing reference paper 
- [ ] HillClimbAlgorithm
   - Missing reference URL
   - Missing reference paper

**Comment by firefly-cpp** [comment]
@kb2623 please check this issue.

**Comment by GregaVrbancic** [comment]
Some algorithms documentation is still without reference paper and/or without reference URL. In some cases, setParameters function arguments are not documented.

**Comment by bahaeddinturkoglu** [comment]
Which file contains the 'Runner' function ?

**Comment by GregaVrbancic** [comment]
Hello @bahaeddinturkoglu, 

the Runner utility can be found in [NiaPy/__init__.py](
https://github.com/NiaOrg/NiaPy/blob/master/NiaPy/__init__.py).

**Comment by GregaVrbancic** [comment]
Refer to issue #188
