### ISSUE TITLE
Hybrid Bat Algorithm coding mistake?

### ISSUE THREAD

**Issue by kivancguckiran** [NiaOrg/NiaPy#156]
Hello everyone, and thanks for the great library.

So I've been tinkering around the source code and I've came across to this:

hba.py Line 58:
`if Fitness[i] <= f_new and self.rand() < self.A: Sol[i], Fitness[i] = S, f_new`

This leads to accepting worse conditions. I think it should be:
`if f_new <= Fitness[i] and self.rand() < self.A: Sol[i], Fitness[i] = S, f_new`

Same condition on ba.py Line 80:
`if (Fnew <= Fitness[i]) and (self.rand() < self.A): Sol[i], Fitness[i] = S[i], Fnew`

What do you think?

In addition to this, I was checking the paper of the [HBA](https://arxiv.org/pdf/1303.6310.pdf).
I've noticed that there are also loudness and pulse emission rates for each bat. Also, they change on iteration. But here I see there is only one loudness and pulse emission rate for the population as a whole.

If you think like this as well, I can try to create a PR about it.

Thank you again!

**Comment by GregaVrbancic** [comment]
Hello @kivancguckiran!

Thank you for kind words about NiaPy. We are still in the early stages of development, and we try to do our best to deliver the best possible library. 

We would be glad if you could create a PR fixing the mentioned error.

Thank you for showing the interest in our library!

**Comment by kivancguckiran** [comment]
So the pull request fixes the above issue. I will focus on the implementation of the paper, the rates and loudnesses if I can.

**Comment by GregaVrbancic** [comment]
Thank you for PR. Sure, go ahead, we would be very happy.
