### ISSUE TITLE
New mechanism for stopCond and old best values

### ISSUE THREAD

**Issue by kivancguckiran** [NiaOrg/NiaPy#168]
Hello,

I'm struggling about two things recently. First is that I cannot order to stop optimization if the best solution achieves a minimum/maximum value. The stop condition only depends on the function evaluation or generation count.

The other thing is that I want  to see the error decreasing over iterations. Since we are not storing the best values in the algorithm, we cannot do this currently.

Is there anything that I'm not aware of, achieves these? I would like to help if these might be added to the library, but with a guidance, since I'm not sure of how big the impact would be.

Thanks as always.

**Comment by kivancguckiran** [comment]
Hello @firefly-cpp !

I will check out the GUI. Seems promising. Both issues I've mentioned would be addressed in a timely manner I guess then.

Thanks again.

**Comment by firefly-cpp** [comment]
Hi @kivancguckiran,

all issues will be addressed within one week.

**Comment by firefly-cpp** [comment]
Hi @kivancguckiran,

A new mechanism has already been incorporated. Please check the following example out
 [example](https://github.com/NiaOrg/NiaPy/blob/master/examples/stopping_criterions.py)

**Comment by kivancguckiran** [comment]
Great!

How are you planning to handle the insight of results?

**Comment by firefly-cpp** [comment]
@kivancguckiran 

This is the next step. :+1:

**Comment by firefly-cpp** [comment]
Hi @kivancguckiran 

Did you think about having the following arrays with log values?

 [example](https://github.com/NiaOrg/NiaPy/blob/master/examples/log_results.py)

**Comment by kivancguckiran** [comment]
Thanks for the implementation. I've tried it and it works. We store the value when an improvement on the best happens right? This way we also optimize memory usage. Looking good.

I think this pretty much covers my requirements. Thanks again, guess we can close the issue.

**Comment by firefly-cpp** [comment]
Hi @kivancguckiran,

yes. You are right. Every improvement is stored.

I am also going to test other scenarios (different termination conditions + storing improvements).

Thanks for your attention.
