### ISSUE TITLE
Logger

### ISSUE THREAD

**Issue by rhododendrom** [NiaOrg/NiaPy#178]
Logger not working, when optType set to "MAXIMIZATION".

It outputs "inf".

**Comment by firefly-cpp** [comment]
Hi @kb2623,

please fix this issue.

**Comment by rhododendrom** [comment]
This issue can be closed.

I have checked the functionality and it works very well.

Thank you.

**Comment by GregaVrbancic** [comment]
@rhododendrom thank you!
