### ISSUE TITLE
Is is possible to manually initialize the population?

### ISSUE THREAD

**Issue by jhmenke** [NiaOrg/NiaPy#179]
Is there a possibility to set an initial population manually or define a function which generates an individual from scratch?

I guess it would be modifying NiaPy.algorithms.Individual.generateSolution, but should only replace it for the initial solution candidates. Has anyone tried this?

My problem is binary but feasible candidates have a high 0 : 1 ratio, i suspect random initialization generates roughly the same amounts of 0 and 1 (rounded from float).

**Comment by firefly-cpp** [comment]
Hi @jhmenke,

Thank you very much for a very interesting suggestion. We will try to add this
feature in the following days.

**Comment by kb2623** [comment]
Hi @jhmenke 

I am working on update that will have your requested functionality. You can have a look at my repository of [NiaPy](https://github.com/kb2623/NiaPy). There is still a lot of work to be done on old algorithms. So the fix won't reach release so soon.

**Comment by jhmenke** [comment]
that was quick, thanks! i will take a look and give feedback

**Comment by jhmenke** [comment]
May i ask what the status of the issue is?
I have seen promising commit messages: https://github.com/kb2623/NiaPy/commit/bfee01beef0e5330153115e6d870a57fdb4377c3

**Comment by GregaVrbancic** [comment]
Hi @jhmenke, thank you again for showing the interest in our micro-framework.  @kb2623 is working actively on this functionality. As soon as we reach the release phase, we will let you know.

**Comment by kb2623** [comment]
Now you can pass a function for population initialization to all algorithms. You have to pass `InitPopFunc` parameter to `setParameters` function or to algorithms constructor.

**Comment by jhmenke** [comment]
Will try asap! Thank you for your time!

**Comment by GregaVrbancic** [comment]
@jhmenke the pull request addressing the issues is now merged into the master branch. 

Please, try it out and give us some feedback.

**Comment by FlorianShepherd** [comment]
> @jhmenke the pull request addressing the issues is now merged into the master branch.
> 
> Please, try it out and give us some feedback.

Dear @GregaVrbancic,
I tested the code in behalf of @jhmenke . Thank you so much for adding this feature. It seems to work great :)

However, I wondered why some algorithms didn't support the initPopFunc. Either I did something wrong when creating the task and calling algorithm.run(task) or it is really not supported (yet). I noticed this for PSO and MFO for example. Maybe others as well.

I fixed this for the PSO here:
https://github.com/FlorianShepherd/NiaPy/commit/9cbe0716925bb0c198f92c41f4ba76a80f2fbc15

All I had to do was to add "InitPopFunc" to "setParameters".

Also I added the option "binary" for the PSO, which rounds the velocity V to integers. This way I can use the PSO as a binary PSO like here: https://pyswarms.readthedocs.io/en/latest/examples/feature_subset_selection.html#using-binary-pso

**Comment by GregaVrbancic** [comment]
Dear @FlorianShepherd,

thank you very much for taking an effort and testing out the new feature 😃 Regarding the problem with some algorithms, we will take a look at it as soon as possible. 

The "binary" option for the PSO also looks promising, we might also integrate it into NiaPy.

**Comment by FlorianShepherd** [comment]
Probably it is just my mistake. I (have to) run the optimization like this, otherwise my initFunc() is not called:

```
from NiaPy.algorithms.basic.pso import ParticleSwarmAlgorithm

    task = Mytask(max_evals=max_evals, D=D, NP=NP, nGEN=nGEN,
                  benchmark=benchmark_class(), InitPopFunc=initfunc, binary=True)
    alg = ParticleSwarmAlgorithm(max_evals=max_evals, D=D, NP=NP, nGEN=nGEN,
                  benchmark=benchmark_class(), InitPopFunc=initfunc, binary=True)
    alg.setParameters(max_evals=max_evals, D=D, NP=NP, nGEN=nGEN,
                  benchmark=benchmark_class(), InitPopFunc=initfunc, binary=True)
    result, _ = alg.run(task=task)
```

It seems like I have to call each function with the same parameters, otherwise an inconsistent default value is used.

**Comment by jhmenke** [comment]
thanks for the updates! i have tried PSO and it works well with the initlization!

there are some problems with other algorithms with the new initialization, e.g. the artificial bee colony. due to the _Foods_ now being a numpy array, the algorithm is broken.

`newSolution.x[param2change] = Foods[i].x[param2change] + (-1 + 2 * self.rand()) * (Foods[i].x[param2change] - Foods[neighbor].x[param2change])`

**Comment by GregaVrbancic** [comment]
@jhmenke thanks for the feedback! 

@kb2623 could you take a look at this?

**Comment by kb2623** [comment]
Hi. 

I have added missing code to algorithms that where not using passed function for population initialization. 

If you want to write a problem specific algorithm, you can rewrite `initPopulation` method form algorithm you are trying to solve a specific problem. For examples on how to rewrite `initPopulation`method you can check other algorithms. For example I suggest that you check `CamelAlgorithm` or `FishSchoolSearch` algorithms.

**Comment by GregaVrbancic** [comment]
@all-contributors please add @jhmenke for question

**Comment by GregaVrbancic** [comment]
The example of custom initialization of population is available [here](https://github.com/NiaOrg/NiaPy/blob/master/examples/custom_init_population.py).
