### ISSUE TITLE
How to plot the convergence?

### ISSUE THREAD

**Issue by brett18618** [NiaOrg/NiaPy#220]
Thank you for your work first. Could you tell me is there a method to plot the convergence with x axis is iteration numbers and y is the fitness function values?

**Comment by firefly-cpp** [comment]
Hi @brett18618 ,

Thanks!

Convergence plot is captured in this example. However, it is tailored to the nFES.

[EXAMPLE](https://github.com/NiaOrg/NiaPy/blob/master/examples/run_pso.py)

Do you prefer number of iterations on x?

**Comment by brett18618** [comment]
Thank you for your reply！I want to observe the convergence curve as the
iteration number changed, is it possible to do that?
Regards
Brett

**Comment by firefly-cpp** [comment]
Yes. It is possible. 

We have to add a new method. Please give us a couple of days to complete this issue.

**Comment by brett18618** [comment]
Many thanks! Do you mind telling me when  it is completed ?

**Comment by firefly-cpp** [comment]
@brett18618 - Yes.

**Comment by brett18618** [comment]
And by the way, I was thinking each iteration corresponds one time
evaluation which is actually the fitness function. It seemed I was wrong
because when I set 100 iterations, the evaluations returned were only 58.
Would you like to explain  me the relationship between the number of
evaluation and that of iteration?

**Comment by firefly-cpp** [comment]
nFES counts each call of fitness function.

**Comment by brett18618** [comment]
So does that mean the fitness function would not be called in each
iteration?

**Comment by GregaVrbancic** [comment]
@brett18618  we have added functionality (function ```return_conv```) to the StoppingTask, which enables the retrieval of values for x and y axis for plotting the covariance graph.

**Comment by GregaVrbancic** [comment]
@all-contributors add @brett18618 for question
