### ISSUE TITLE
module not found error

### ISSUE THREAD

**Issue by musawakiliML** [NiaOrg/NiaPy#224]
### Actual behavior
--------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-3-4132b179b7f7> in <module>()
      1 import random
      2 from NiaPy.algorithms.basic import FlowerPollinationAlgorithm
----> 3 from NiaPy.task.task import StoppingTask, OptimizationType
      4 from NiaPy.benchmarks import Sphere
      5 

ModuleNotFoundError: No module named 'NiaPy.task'

**Comment by GregaVrbancic** [comment]
Hi @musawakiliML,

could you provide us with the example script which you are trying to run?

**Comment by GregaVrbancic** [comment]
@all-contributors please add @musawakiliML for question

**Comment by GregaVrbancic** [comment]
@all-contributors please add @musawakiliML for question

**Comment by GregaVrbancic** [comment]
Closing the issue due to the inactivity.

**Comment by musawakiliML** [comment]
![Opera Snapshot_2019-12-20_211531_colab research google com](https://user-images.githubusercontent.com/19978292/71289772-42a97d00-236e-11ea-9d15-7e6765eb4d07.png)

**Comment by Ultron-Legacy** [comment]
Did you find the solution?
