### ISSUE TITLE
No module named 'NiaPy.task'

### ISSUE THREAD

**Issue by musawakiliML** [NiaOrg/NiaPy#245]
![Opera Snapshot_2019-12-20_211531_colab research google com](https://user-images.githubusercontent.com/19978292/71289854-81d7ce00-236e-11ea-8c20-aca112b202dd.png)

**Comment by GregaVrbancic** [comment]
Hi, I would presume that you are not using the latest RC version of NiaPy library, so first I would recommend you to install it with: ```pip install NiaPy==2.0.0rc10```. Please let me know if that solves your problem.

**Comment by musawakiliML** [comment]
thank you very much it did worked by installing the latest version as stated.
![Screenshot from 2019-12-22 11-08-53](https://user-images.githubusercontent.com/19978292/71320434-80f88680-24ab-11ea-8f88-9a0478827f27.png)
