### ISSUE TITLE
BAT Optimization Algorithm

### ISSUE THREAD

**Issue by RamziAI** [NiaOrg/NiaPy#285]
Hello. I tried to use the BAT Optimization Algorithm and I expected to get approximately 0, with such benchmark functions as Rosebrock and Ackley, a number of iterations 66000. But the result I get is much higher. I wanted to know is it because of code, or by the algorithm itself?

**Comment by sisco0** [comment]
Could you please post your demo code?

**Comment by RamziAI** [comment]
Done, thanks for your attention.

пт, 8 янв. 2021 г. в 21:51, sisco0 <notifications@github.com>:

**Comment by firefly-cpp** [comment]
Duplicated issue. See #286
