### ISSUE TITLE
BFOA implementation

### ISSUE THREAD

**Issue by firefly-cpp** [NiaOrg/NiaPy#288]
The results of BFOA implementation are not consistent with the results found in related work. @zStupan is now working on the fix.

**Comment by zStupan** [comment]
I have fixed the issue. The results of the current implementation are now consistent with my own c++ and python implementations of the algorithm, as well as the C implementation found in: [https://github.com/poluyan/BFOA](https://github.com/poluyan/BFOA) and the Ruby implementation found in the book Clever Algorithms by Jason Brownlee ([https://github.com/clever-algorithms/CleverAlgorithms](https://github.com/clever-algorithms/CleverAlgorithms))

**Comment by firefly-cpp** [comment]
Brilliant! Thank you very much.
