### ISSUE TITLE
Several TODOs in ca.py

### ISSUE THREAD

**Issue by firefly-cpp** [NiaOrg/NiaPy#306]
There exist several TODOs in Camel Algorithm (ca.py).

**Comment by firefly-cpp** [comment]
Has anyone experience with this algorithm?

**Comment by sisco0** [comment]
I did not, I let the reference here for the file and the paper for future research of someone interested.
https://github.com/NiaOrg/NiaPy/blob/22fa3eef1ff38f6b5f8eebdd8aa10e6593b8da98/NiaPy/algorithms/basic/ca.py
https://www.iasj.net/iasj/download/e32775e0eef3d2eb

**Comment by zStupan** [comment]
I'm planning to document all the undocumented parameters as part of the PEP8 refactor. There's quite a few in the project.

In CA, T_min and T_max are minimum and maximum temperature and omega is the burden factor.
