### ISSUE TITLE
NiaPy fails to build with Python 3.10.0a7.

### ISSUE THREAD

**Issue by firefly-cpp** [NiaOrg/NiaPy#308]
FYI: https://bugzilla.redhat.com/show_bug.cgi?id=1953902

**Comment by zStupan** [comment]
Strange. This was a bug with pipenv but as I understand it has been fixed (https://github.com/pypa/pipenv/issues/4379)

**Comment by zStupan** [comment]
This is fixed in  #316, I think.

**Comment by GregaVrbancic** [comment]
Correct, this should be resolved in #316. I think we can close this issue, and if the problem still occurs, we can reopen this issue.
