### ISSUE TITLE
Create a new release

### ISSUE THREAD

**Issue by firefly-cpp** [NiaOrg/NiaPy#310]
@GregaVrbancic please create a new release (when you have a time).

**Comment by GregaVrbancic** [comment]
Sure, I will do it later today.

Additionally, we should also fix the API documentation. When rc14 was released the docs were ok (https://niapy.readthedocs.io/en/2.0.0rc14/api/algorithms.html), while the latest version is having some problems (https://niapy.readthedocs.io/en/2.0.0rc14/api/algorithms.html). I have taken a quick look at the readthedocs build logs and everything looks fine, so there must be some issue in the configuration or something.
