### ISSUE TITLE
niapy import fails for Python 3.6.x

### ISSUE THREAD

**Issue by lukapecnik** [NiaOrg/NiaPy#311]
**Steps to reproduce**
`import niapy` using Python 3.6.x

**Expected behavior**
NiaPy should be imported.

**Actual behavior**
Error occurs:
```
>>> import niapy
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "E:\Python36\lib\site-packages\niapy\__init__.py", line 5, in <module>
    from niapy import util, algorithms, benchmarks, task
  File "E:\Python36\lib\site-packages\niapy\util\__init__.py", line 3, in <module>
    from niapy.util.argparser import get_argparser, get_args, get_args_dict
  File "E:\Python36\lib\site-packages\niapy\util\argparser.py", line 12, in <module>
    from niapy.task import OptimizationType
  File "E:\Python36\lib\site-packages\niapy\task.py", line 12, in <module>
    import niapy.util.repair as repair
AttributeError: module 'niapy' has no attribute 'util'
```

**System configuration**

 - OS: Windows
 - Python version: 3.6.8

**NOTE**
I also tested Python 3.7.x and 3.8.x and it seems to be working there.

**Comment by firefly-cpp** [comment]
Thank you @lukapecnik for reporting this issue.

@zStupan What do you think?

**Comment by zStupan** [comment]
Aliasing niapy.util.repair as repair seemed to be the problem. Fixed in #312

**Comment by lukapecnik** [comment]
@zStupan could you please create a new release?

**Comment by firefly-cpp** [comment]
@GregaVrbancic, please create a new release.

**Comment by GregaVrbancic** [comment]
Release was created.

@all-contributors please add @lukapecnik  as a bug reporter.
