### ISSUE TITLE
Remove ThrowingTask and CountingTask

### ISSUE THREAD

**Issue by zStupan** [NiaOrg/NiaPy#317]
I feel like the `ThrowingTask` and the `CountingTask` should be removed, and only the `StoppingTask` should be kept. The Counting task is an unnecessary level of inheritance between `Task` and `StoppingTask`, and the ThrowingTask isn't used in any project, I doubt there's an actual use case for it.

My suggestion is, we keep only the StoppingTask and just name it Task. No inheritance needed.

What do you think?

**Comment by GregaVrbancic** [comment]
I have also never used any other than StoppingTask, so from the application standpoint I don't think it's needed. But maybe there are some advantages of having those tasks for benchmarking different algorithms?  @firefly-cpp what is your point of view on this?

**Comment by firefly-cpp** [comment]
Hello all.

I totally support this idea. We need only Task. Thanks for pointing this issue out.

**Comment by zStupan** [comment]
Fixed in #323
