### ISSUE TITLE
BA, CS and FA implementations are incorrect

### ISSUE THREAD

**Issue by zStupan** [NiaOrg/NiaPy#341]
Our implementation of cuckoo search is inconsistent with the [authors implementation](https://www.mathworks.com/matlabcentral/fileexchange/74767-the-standard-cuckoo-search-cs?s_tid=prof_contriblnk). Every individual from the population should be moved by levy flights not just one random one. Also, in his implementation the empty nests procedure generates new solution  by biased random walks, while in ours they're just uniformly distributed in the search space.

I think other implementations of Yangs algorithms might be wrong too, I haven't tested them yet. But BA, FA and FPA should also be looked at and compared with the matlab code ([available here](https://www.mathworks.com/matlabcentral/profile/authors/3659939)). 

EDIT1: The Bat Algorithm is also missing some steps. In the [original article ](https://arxiv.org/pdf/1004.4170.pdf) and the matlab code by Yang, that I linked above, the pulse rate and loudness are updated each iteration.

EDIT2: The firefly algorithm also gives completely different results than the matlab implementation. The FPA seems to be working fine.

**Comment by firefly-cpp** [comment]
@zStupan, you are probably right. Version 1.0 was consistent with the original implementation, 
while some of the future attempts are slightly different (new coding style, new interface, new contributors, 
numpy, etc.). We tried to solve this challenge in the following issue #188. However, time constraints 
did not allow us to do finish this task.

In a nutshell, please go ahead and check consistency of these algorithms. 

We may also open a similar issue as it was raised in issue #188

**Comment by zStupan** [comment]
@firefly-cpp I fixed these ones.

The problem is that more often than not, pseudocode is the only thing you can work with, because most researchers don't provide the code they used for their experiments. And the pseudocode can be very unclear so you have to guess what the author meant.

The checklist is a great idea, because unit tests miss bugs like this.
