### ISSUE TITLE
Second stable release

### ISSUE THREAD

**Issue by firefly-cpp** [NiaOrg/NiaPy#359]
Before we enter New Year, I suggest we finally release the second stable release of niapy.

What do others think?

**Comment by firefly-cpp** [comment]
@GregaVrbancic, @zStupan

**Comment by GregaVrbancic** [comment]
@firefly-cpp today I will create release for stable v2, if that's ok.

**Comment by firefly-cpp** [comment]
Perfect, @GregaVrbancic!

**Comment by GregaVrbancic** [comment]
v2 stable release is created and ready to install via pip or conda 😃 I have also opened a new [discussion](https://github.com/NiaOrg/NiaPy/discussions/360) for things which could be done in next version 2.1.0 .
