### ISSUE TITLE
Logging not working if optimization type set to maximization 

### ISSUE THREAD

**Issue by rhododendrom** [NiaOrg/NiaPy#367]
No logging is provided in case of following:

task = Task(problem=ff_value(dimension=10, lower=0, upper=1),
            max_evals=100, enable_logging=True, optimization_type=OptimizationType.MAXIMIZATION)

**Comment by firefly-cpp** [comment]
@zStupan, please check it out.

**Comment by zStupan** [comment]
@rhododendrom It works for me on python3.10 and a fresh install of the latest niapy release, which version of python are you using? Could you also please share the implementation of `ff_value`?
```python
from niapy.task import Task, OptimizationType
from niapy.problems import Sphere
from niapy.algorithms.basic import DifferentialEvolution


algorithm = DifferentialEvolution(population_size=50, differential_weight=0.8, crossover_probability=0.9)
problem = Sphere(10, 0, 1)
task = Task(problem, max_evals=100, optimization_type=OptimizationType.MAXIMIZATION, enable_logging=True)

algorithm.run(task)
```

Should provide the output:
```
INFO:niapy.task.Task:evals:1 => 3.241297708781705
INFO:niapy.task.Task:evals:2 => 3.577608409031643
INFO:niapy.task.Task:evals:4 => 5.588174037929252
INFO:niapy.task.Task:evals:17 => 5.747700926113583
INFO:niapy.task.Task:evals:85 => 5.766053703015857
INFO:niapy.task.Task:evals:95 => 6.401214995854259

```

**Comment by rhododendrom** [comment]
Got it. I've had some installation troubles lately with the latest release and I was using the 2.0.0rc17 version.
Now, after upgrade, everything is fine.

Thanks and sorry about that
