### ISSUE TITLE
all-contributors

### ISSUE THREAD

**Issue by firefly-cpp** [NiaOrg/NiaPy#375]
@all-contributors please add @carlosal1015 and @firefly-cpp for platform

**Comment by firefly-cpp** [comment]
@GregaVrbancic, please review commands.

**Comment by GregaVrbancic** [comment]
@all-contributors add @carlosal1015 for platform

**Comment by GregaVrbancic** [comment]
@all-contributors add @carlosal1015 for platform

**Comment by GregaVrbancic** [comment]
https://github.com/all-contributors add @firefly-cpp for platform

**Comment by GregaVrbancic** [comment]
> @GregaVrbancic, please review commands.

As far as I know, bot can only handle one user request per comment.

**Comment by GregaVrbancic** [comment]
@all-contributors add @firefly-cpp for platform
