### ISSUE TITLE
Whale Optimization Algorithm (WOA) and Sparrow Search Algorithm (SSA) implementation

### ISSUE THREAD

**Issue by hanamthang** [NiaOrg/NiaPy#378]
Hi there,

Could you consider to test and add the WOA and SSA algorithms in the future version of NiaPy? 

Many thanks,
Thang

**Comment by firefly-cpp** [comment]
Hi @hanamthang,

thank you very much for raising this issue. However, I (speaking for myself) do not want to give a special attention to the "new"; "novel"; metaphor-based nature-inspired algorithms. Currently, there exist several metaphor-based nature-inspired algorithms in niapy framework. In contrary, we would like to add more recent state-of-the-art variants of algorithms, e.g. recent winners of CEC competitions, etc.

**Comment by firefly-cpp** [comment]
I will close this thread now. Please open again for further discussion.
