### ISSUE TITLE
Bump version to 2.0.3

### ISSUE THREAD

**Issue by firefly-cpp** [NiaOrg/NiaPy#392]

**Comment by GregaVrbancic** [comment]
Will do release ASAP

**Comment by firefly-cpp** [comment]
@GregaVrbancic, please release the latest version also on PyPI.

**Comment by GregaVrbancic** [comment]
We have to fix the build before, because it is needed to build package which is pushed to pypi.

**Comment by firefly-cpp** [comment]
@GregaVrbancic, do we have the green light now to provide another version and pip package after the recent changes? Are there any additional build problems that prevent package uploading to pip?

**Comment by firefly-cpp** [comment]
@zStupan (tag only to receive notifications on this issue)

**Comment by GregaVrbancic** [comment]
Thanks to @zStupan the build for release 2.0.4 was successfully created and pushed to pypi and conda.
